---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  tasks:
   - name: Install SNMP RPMs for ubuntu version 20
     apt:
      name: snmpd
      state: present
     when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "20")
	 
   - name: Install SNMP RPMs for Amazon Linux 2
     yum: name={{ item }} state=present
     with_items:
      - net-snmp
      - net-snmp-utils
	 when: (ansible_distribution == "Amazon" and ansible_distribution_major_version == "2")
	 
   - name: Install SNMP RPMs for ubuntu version 14.04
     shell: |
      apt-get install snmpd libsnmp30 libsnmp-base
	 when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")
	 
   - name: Install SNMP RPMs for ubuntu version 18.04
     apt:
	  name: snmpd
	  state: present
	 when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18")
	 
   - name: Configuring the snmpd
     shell: |
	  mv /etc/snmp/snmpd.conf /etc/snmp/snmpd.conf_old
      touch /etc/snmp/snmpd.conf
      cat <<EOT >> /etc/snmp/snmpd.conf
      #NMPv1 and v2 are not allowed at Granicus
      #group   notConfigGroup v1            notConfigUser
      #group   notConfigGroup v2c           notConfigUser
      view    systemview    included   .1.3.6.1.2.1.1
      view    systemview    included   .1.3.6.1.2.1.25.1.1
      access  notConfigGroup “”      any       noauth    exact  systemview  none  none
      dontLogTCPWrappersConnects yes
      #includeDir /etc/snmp/local_config
      rouser     asysp-snmp
      createUser asysp-snmp SHA “h54G54bMBuY59yd6" AES h54G54bMBuY59yd6
      EOT
   - name: Restart snmpd
     shell: |
	  sudo service snmpd restart
~                                                 